# syntax=docker/dockerfile:1.7

# ---------- Stage 1: install deps ----------
FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
# Use `npm install --legacy-peer-deps` rather than `npm ci`:
#   1. `npm ci` does a strict lock-integrity check that rejects locks
#      generated by a newer npm than the install environment ships
#      (node:22-alpine has npm 10.9.x; locks from npm 11 trigger
#      "Missing: <pkg> from lock file" even though the entries exist).
#   2. `--legacy-peer-deps` is required regardless because better-auth@1.6.9
#      peer-wants drizzle-orm@^0.45.2 but the project pins ^0.41.0; without
#      the flag npm aborts on peer drift. Drift tracked in
#      docs/specs/current_repo_state_2026-04-29.md §J.1 — real fix is the
#      drizzle-orm 0.41 → 0.45 upgrade, deferred.
#   3. We do NOT pass --omit=optional. lightningcss ships platform-specific
#      native binaries as optional deps; Tailwind v4's postcss plugin needs
#      the matching binary at build time.
# Cost vs `npm ci`: ~5-15s slower (re-resolves the tree) but tolerant of
# lock-format/version skew, which has bitten this deploy twice now.
RUN npm install --legacy-peer-deps --no-audit --no-fund

# ---------- Stage 2: build ----------
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Render does NOT pass dashboard env vars to Docker builds by default
# (only to runtime). `next build` imports every route, which loads
# `src/lib/env.ts` (zod) and `src/db/client.ts` (throws if DATABASE_URL
# unset). Inject build-only dummy values that satisfy validation; real
# values are bound at runtime by Render.
ENV DATABASE_URL="postgres://dummy:dummy@localhost:5432/dummy"
ENV DATABASE_ADMIN_URL="postgres://dummy:dummy@localhost:5432/dummy"
ENV BETTER_AUTH_SECRET="build_dummy_secret_at_least_32_chars_long_xxxxx"
ENV BETTER_AUTH_URL="http://localhost:3000"
ENV NEXT_PUBLIC_APP_URL="http://localhost:3000"
ENV R2_ACCOUNT_ID="dummy"
ENV R2_ACCESS_KEY_ID="dummy"
ENV R2_SECRET_ACCESS_KEY="dummy"
ENV R2_BUCKET_NAME="dummy"
ENV UPSTASH_REDIS_REST_URL="http://localhost:8079"
ENV UPSTASH_REDIS_REST_TOKEN="dummy"
ENV TAX_ID_ENCRYPTION_KEY="dummy"
ENV TRIGGER_SECRET_KEY="dummy"
RUN npm run build

# ---------- Stage 3: runtime ----------
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Standalone output bundles only what's needed
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
