# syntax=docker/dockerfile:1.7

# ---------- Stage 1: install deps ----------
FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
# Match the lockfile generator. node:22-alpine ships npm 10.9.x, which
# rejects lock files generated by npm 11 (new optional-deps metadata
# format). Pinning npm 11 here makes `npm ci` accept locks generated
# locally on npm 11+. Symptom of mismatch: "Missing: <package> from lock
# file" for a long list of platform-optional deps.
RUN npm install -g npm@11
# We do NOT pass --omit=optional. lightningcss ships its platform-
# specific native binaries (lightningcss.linux-x64-musl.node, etc.) as
# optional deps; Tailwind v4's postcss plugin requires the matching
# binary at build time, so omitting optional breaks `next build`.
RUN npm ci

# ---------- Stage 2: build ----------
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Render does NOT pass dashboard env vars to Docker builds by default
# (only to runtime). `next build` imports every route, which loads
# `src/lib/env.ts` (zod) and `src/db/client.ts` (throws if DATABASE_URL
# unset). Inject build-only dummy values that satisfy validation; real
# values are bound at runtime by Render.
ENV DATABASE_URL="postgres://dummy:dummy@localhost:5432/dummy"
ENV DATABASE_ADMIN_URL="postgres://dummy:dummy@localhost:5432/dummy"
ENV BETTER_AUTH_SECRET="build_dummy_secret_at_least_32_chars_long_xxxxx"
ENV BETTER_AUTH_URL="http://localhost:3000"
ENV NEXT_PUBLIC_APP_URL="http://localhost:3000"
ENV R2_ACCOUNT_ID="dummy"
ENV R2_ACCESS_KEY_ID="dummy"
ENV R2_SECRET_ACCESS_KEY="dummy"
ENV R2_BUCKET_NAME="dummy"
ENV UPSTASH_REDIS_REST_URL="http://localhost:8079"
ENV UPSTASH_REDIS_REST_TOKEN="dummy"
ENV TAX_ID_ENCRYPTION_KEY="dummy"
ENV TRIGGER_SECRET_KEY="dummy"
RUN npm run build

# ---------- Stage 3: runtime ----------
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Standalone output bundles only what's needed
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
