import { and, asc, eq, gte, lte } from "drizzle-orm";
import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { Readable } from "node:stream";
import archiver from "archiver";
import { GetObjectCommand } from "@aws-sdk/client-s3";

import { auth } from "@/auth/config";
import { db } from "@/db/client";
import { documents, users } from "@/db/schema";
import { writeAuditEvent } from "@/domain/audit";
import { getEffectiveContext } from "@/domain/context";
import { AuthorizationError, assertCan } from "@/domain/permissions";
import { r2, R2_BUCKET } from "@/lib/storage";

// Project photos ZIP export.
//
// Scope: all documents with documentType='photo_log' for the project,
// optionally filtered by createdAt via ?from=YYYY-MM-DD&to=YYYY-MM-DD
// (inclusive, end-of-day on `to`). Step 21 will introduce a first-class
// `category='photos'` enum; keeping the filter on documentType for now
// means a single line swap when that lands.
//
// Streaming: archiver pipes R2 GetObject bodies directly into the ZIP
// without buffering. Each photo is placed at its original storage key
// tail ("{n}-{title}.ext" style), and an `index.txt` is prepended with a
// human-readable manifest (photo #, title, uploader, timestamp).

export const runtime = "nodejs";

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function safeFilename(s: string): string {
  return s.replace(/[\\/:*?"<>|]/g, "_").slice(0, 140);
}

function parseDate(v: string | null): Date | null {
  if (!v) return null;
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? null : d;
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ projectId: string }> },
) {
  const { projectId } = await params;
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) {
    return NextResponse.json({ error: "unauthenticated" }, { status: 401 });
  }

  try {
    const ctx = await getEffectiveContext(
      session.session as unknown as { appUserId?: string | null },
      projectId,
    );
    assertCan(ctx.permissions, "document", "read");

    const url = new URL(req.url);
    const from = parseDate(url.searchParams.get("from"));
    const toRaw = parseDate(url.searchParams.get("to"));
    // Inclusive end-of-day for `to` so ?to=2026-04-17 includes that day.
    const to = toRaw
      ? new Date(
          toRaw.getFullYear(),
          toRaw.getMonth(),
          toRaw.getDate(),
          23,
          59,
          59,
          999,
        )
      : null;

    const whereClauses = [
      eq(documents.projectId, projectId),
      eq(documents.documentType, "photo_log"),
      eq(documents.documentStatus, "active"),
    ];
    if (from) whereClauses.push(gte(documents.createdAt, from));
    if (to) whereClauses.push(lte(documents.createdAt, to));

    const rows = await db
      .select({
        id: documents.id,
        title: documents.title,
        storageKey: documents.storageKey,
        createdAt: documents.createdAt,
        uploaderName: users.displayName,
        uploaderEmail: users.email,
      })
      .from(documents)
      .leftJoin(users, eq(users.id, documents.uploadedByUserId))
      .where(and(...whereClauses))
      .orderBy(asc(documents.createdAt));

    const today = new Date().toISOString().slice(0, 10);
    const projectSlug = slug(ctx.project.name);
    const zipFilename = `photos-${projectSlug}-${today}.zip`;

    const archive = archiver("zip", { zlib: { level: 6 } });

    const indexLines: string[] = [
      `Project: ${ctx.project.name}`,
      `Generated: ${new Date().toISOString()}`,
      `Generated by: ${ctx.user.displayName ?? ctx.user.email}`,
      from ? `From: ${from.toISOString().slice(0, 10)}` : "From: (earliest)",
      to ? `To: ${to.toISOString().slice(0, 10)}` : "To: (latest)",
      `Photo count: ${rows.length}`,
      "",
      "#\tFilename\tTitle\tUploaded at\tUploaded by",
    ];

    rows.forEach((row, i) => {
      const n = String(i + 1).padStart(3, "0");
      const ext = row.storageKey.match(/\.[a-z0-9]+$/i)?.[0] ?? "";
      const filename = `${n}-${safeFilename(row.title || row.id)}${ext}`;
      indexLines.push(
        [
          n,
          filename,
          row.title || "",
          row.createdAt.toISOString(),
          row.uploaderName ?? row.uploaderEmail ?? "",
        ].join("\t"),
      );
    });

    archive.append(indexLines.join("\n"), { name: "index.txt" });

    // Fetch each R2 object and stream it into the archive. Missing objects
    // are logged to a skipped.txt sidecar rather than aborting the export.
    const skipped: string[] = [];
    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      const n = String(i + 1).padStart(3, "0");
      const ext = row.storageKey.match(/\.[a-z0-9]+$/i)?.[0] ?? "";
      const filename = `${n}-${safeFilename(row.title || row.id)}${ext}`;
      try {
        const res = await r2.send(
          new GetObjectCommand({ Bucket: R2_BUCKET, Key: row.storageKey }),
        );
        if (!res.Body) {
          skipped.push(`${filename}\t(empty body)`);
          continue;
        }
        archive.append(res.Body as Readable, { name: filename });
      } catch (err) {
        const msg = err instanceof Error ? err.message : "fetch failed";
        skipped.push(`${filename}\t${msg}`);
      }
    }
    if (skipped.length > 0) {
      archive.append(skipped.join("\n"), { name: "skipped.txt" });
    }

    archive.finalize().catch((err) => {
      console.error("photos archive.finalize failed", err);
      archive.destroy(err as Error);
    });

    await writeAuditEvent(ctx, {
      action: "photos.exported",
      resourceType: "project",
      resourceId: projectId,
      details: {
        metadata: {
          photoCount: rows.length,
          skippedCount: skipped.length,
          from: from?.toISOString() ?? null,
          to: to?.toISOString() ?? null,
        },
      },
    });

    const webStream = Readable.toWeb(archive) as unknown as ReadableStream;
    return new Response(webStream, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${zipFilename}"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (err) {
    if (err instanceof AuthorizationError) {
      const status =
        err.code === "unauthenticated"
          ? 401
          : err.code === "not_found"
            ? 404
            : 403;
      return NextResponse.json(
        { error: err.code, message: err.message },
        { status },
      );
    }
    throw err;
  }
}
